---
swagger: "2.0"
info:
  description: '"Spring Boot REST API for greeting people"'
  version: 1.0.0
  title: Spring Boot REST API
  license:
    name: Apache License Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0"
host: localhost:8080
basePath: /
tags:
- name: character-controller
  description: Character Controller
- name: weapon-controller
  description: Weapon Controller
paths:
  /api/characters:
    get:
      tags:
      - character-controller
      summary: findAllCharacters
      operationId: findAllCharactersUsingGET
      produces:
      - application/json
      parameters: []
      deprecated: false
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
    post:
      tags:
      - character-controller
      summary: createCharacter
      operationId: createCharacterUsingPOST
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: character
        description: character
        required: true
        schema:
          $ref: '#/definitions/Character'
      deprecated: false
      responses:
        "200":
          description: OK
          schema:
            type: object
        "201":
          description: Created
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
  /api/characters/upload/img/{id}:
    get:
      tags:
      - character-controller
      summary: getUploadImg
      operationId: getUploadImgUsingGET
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: string
        format: uuid
      deprecated: false
      responses:
        "200":
          description: OK
          schema:
            type: string
            format: byte
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
  /api/characters/{id}:
    get:
      tags:
      - character-controller
      summary: findCharacterById
      operationId: findCharacterByIdUsingGET
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: string
        format: uuid
      deprecated: false
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Character'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
    put:
      tags:
      - character-controller
      summary: updateCharacter
      operationId: updateCharacterUsingPUT
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: character
        description: character
        required: true
        schema:
          $ref: '#/definitions/Character'
      - name: id
        in: path
        description: id
        required: true
        type: string
        format: uuid
      deprecated: false
      responses:
        "200":
          description: OK
        "201":
          description: Created
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
    delete:
      tags:
      - character-controller
      summary: deleteCharacter
      operationId: deleteCharacterUsingDELETE
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: string
        format: uuid
      deprecated: false
      responses:
        "200":
          description: OK
          schema:
            type: object
        "204":
          description: No Content
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
    patch:
      tags:
      - character-controller
      summary: uploadCharacterImg
      operationId: uploadCharacterImgUsingPATCH
      consumes:
      - multipart/form-data
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: string
        format: uuid
      - name: image
        in: formData
        description: image
        required: true
        type: file
      deprecated: false
      responses:
        "200":
          description: OK
        "204":
          description: No Content
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
  /api/weapons:
    get:
      tags:
      - weapon-controller
      summary: findAllWeapons
      operationId: findAllWeaponsUsingGET
      produces:
      - application/json
      parameters: []
      deprecated: false
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
    post:
      tags:
      - weapon-controller
      summary: createWeapon
      operationId: createWeaponUsingPOST
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: weapon
        description: weapon
        required: true
        schema:
          $ref: '#/definitions/Weapon'
      deprecated: false
      responses:
        "200":
          description: OK
          schema:
            type: object
        "201":
          description: Created
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
  /api/weapons/{id}:
    get:
      tags:
      - weapon-controller
      summary: findWeaponById
      operationId: findWeaponByIdUsingGET
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: string
        format: uuid
      deprecated: false
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Weapon'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
    put:
      tags:
      - weapon-controller
      summary: updateWeapon
      operationId: updateWeaponUsingPUT
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: string
        format: uuid
      - in: body
        name: weapon
        description: weapon
        required: true
        schema:
          $ref: '#/definitions/Weapon'
      deprecated: false
      responses:
        "200":
          description: OK
        "201":
          description: Created
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
    delete:
      tags:
      - weapon-controller
      summary: deleteWeapon
      operationId: deleteWeaponUsingDELETE
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: string
        format: uuid
      deprecated: false
      responses:
        "200":
          description: OK
          schema:
            type: object
        "204":
          description: No Content
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
definitions:
  Character:
    type: object
    properties:
      birthday:
        type: string
        format: date
        example: 0000-09-13
        description: birthday
      name:
        type: string
        example: Albedo
        description: name
      nation:
        type: string
        example: Mondstadt
        description: nation
      rarity:
        type: integer
        format: int32
        example: 5
        description: rarity
      title:
        type: string
        example: Kreideprinz
        description: title
      vision:
        type: string
        example: Geo
        description: vision
      weapon:
        type: string
        example: Sword
        description: weapon
    title: Character
  ResponseEntity:
    type: object
    properties:
      body:
        type: object
        properties: {}
      statusCode:
        type: string
        enum:
        - 100 CONTINUE
        - 101 SWITCHING_PROTOCOLS
        - 102 PROCESSING
        - 103 CHECKPOINT
        - 200 OK
        - 201 CREATED
        - 202 ACCEPTED
        - 203 NON_AUTHORITATIVE_INFORMATION
        - 204 NO_CONTENT
        - 205 RESET_CONTENT
        - 206 PARTIAL_CONTENT
        - 207 MULTI_STATUS
        - 208 ALREADY_REPORTED
        - 226 IM_USED
        - 300 MULTIPLE_CHOICES
        - 301 MOVED_PERMANENTLY
        - 302 FOUND
        - 302 MOVED_TEMPORARILY
        - 303 SEE_OTHER
        - 304 NOT_MODIFIED
        - 305 USE_PROXY
        - 307 TEMPORARY_REDIRECT
        - 308 PERMANENT_REDIRECT
        - 400 BAD_REQUEST
        - 401 UNAUTHORIZED
        - 402 PAYMENT_REQUIRED
        - 403 FORBIDDEN
        - 404 NOT_FOUND
        - 405 METHOD_NOT_ALLOWED
        - 406 NOT_ACCEPTABLE
        - 407 PROXY_AUTHENTICATION_REQUIRED
        - 408 REQUEST_TIMEOUT
        - 409 CONFLICT
        - 410 GONE
        - 411 LENGTH_REQUIRED
        - 412 PRECONDITION_FAILED
        - 413 PAYLOAD_TOO_LARGE
        - 413 REQUEST_ENTITY_TOO_LARGE
        - 414 URI_TOO_LONG
        - 414 REQUEST_URI_TOO_LONG
        - 415 UNSUPPORTED_MEDIA_TYPE
        - 416 REQUESTED_RANGE_NOT_SATISFIABLE
        - 417 EXPECTATION_FAILED
        - 418 I_AM_A_TEAPOT
        - 419 INSUFFICIENT_SPACE_ON_RESOURCE
        - 420 METHOD_FAILURE
        - 421 DESTINATION_LOCKED
        - 422 UNPROCESSABLE_ENTITY
        - 423 LOCKED
        - 424 FAILED_DEPENDENCY
        - 425 TOO_EARLY
        - 426 UPGRADE_REQUIRED
        - 428 PRECONDITION_REQUIRED
        - 429 TOO_MANY_REQUESTS
        - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
        - 451 UNAVAILABLE_FOR_LEGAL_REASONS
        - 500 INTERNAL_SERVER_ERROR
        - 501 NOT_IMPLEMENTED
        - 502 BAD_GATEWAY
        - 503 SERVICE_UNAVAILABLE
        - 504 GATEWAY_TIMEOUT
        - 505 HTTP_VERSION_NOT_SUPPORTED
        - 506 VARIANT_ALSO_NEGOTIATES
        - 507 INSUFFICIENT_STORAGE
        - 508 LOOP_DETECTED
        - 509 BANDWIDTH_LIMIT_EXCEEDED
        - 510 NOT_EXTENDED
        - 511 NETWORK_AUTHENTICATION_REQUIRED
      statusCodeValue:
        type: integer
        format: int32
    title: ResponseEntity
  Weapon:
    type: object
    properties:
      ascensionMaterial:
        type: string
        example: distantant-sea
        description: ascensionMaterial
      baseAttack:
        type: integer
        format: int32
        example: 42
        description: baseAttack
      location:
        type: string
        example: Gacha
        description: location
      name:
        type: string
        example: Akuoumaru
        description: name
      passiveDesc:
        type: string
        example: "For every point of the entire party's combined maximum Energy capacity, the Elemental Burst DMG of the character equipping this weapon is increased by 0.12/0.15/0.18/0.21/0.24%. A maximum of 40/50/60/70/80% increased Elemental Burst DMG can be achieved this way."
        description: passiveDesc
      passiveName:
        type: string
        example: Watatsumi Wavewalker
        description: passiveName
      rarity:
        type: integer
        format: int32
        example: 4
        description: rarity
      subStat:
        type: string
        example: ATK
        description: subStat
      type:
        type: string
        example: Claymore
        description: type
    title: Weapon
